name : 01_helloWorld

on : workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps :
      - name : print a Greeting
        run : echo"hello world Good Afternoon"

      - name : Multiline Greeting
        run : |
          echo"welcome to the Github Action"
          echo"it runs on : $RUNNER_OS"
          echo"the github repo is : $GITHUB_REPOSITORY"
