name : push_trigger

on : push

jobs:
  new_push:
    runs-on: ubuntu-latest
    steps:
      - name: new push is done 
        echo "Event name : $GITHUB_EVENT_NAME"  
          echo "Branch ref : $GITHUB_REF"        
          echo "Commit SHA : $GITHUB_SHA"
          echo "Pushed by  : $GITHUB_ACTOR"

    
